FROM oven/bun:1-slim AS builder
WORKDIR /app

ARG NEXT_PUBLIC_DEFAULT_AVATAR_URL=__NEXT_PUBLIC_DEFAULT_AVATAR_URL__
ARG NEXT_PUBLIC_GITHUB_AUTH_ENABLED=__NEXT_PUBLIC_GITHUB_AUTH_ENABLED__
ARG NEXT_PUBLIC_DISCORD_AUTH_ENABLED=__NEXT_PUBLIC_DISCORD_AUTH_ENABLED__
ARG NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=__NEXT_PUBLIC_GOOGLE_AUTH_ENABLED__
ARG NEXT_PUBLIC_EMAIL_AUTH_ENABLED=__NEXT_PUBLIC_EMAIL_AUTH_ENABLED__
ARG NEXT_PUBLIC_PAYMENTS_ENABLED=__NEXT_PUBLIC_PAYMENTS_ENABLED__
ARG TIERS_JSON='[]'
ARG NEXT_PUBLIC_APP_DESC="__NEXT_PUBLIC_APP_DESC__"
ARG NEXT_PUBLIC_API_URL=__NEXT_PUBLIC_API_URL__
ARG NEXT_PUBLIC_FOOTER_LINKS='{}'
ARG NEXT_PUBLIC_NAVBAR_LINKS='[]'
ARG NEXT_PUBLIC_FRONTEND_URL=__NEXT_PUBLIC_FRONTEND_URL__
ARG NEXT_PUBLIC_APP_NAME=__NEXT_PUBLIC_APP_NAME__
ARG NEXT_PUBLIC_UPLOAD_LIMIT_BYTES=__NEXT_PUBLIC_UPLOAD_LIMIT_BYTES__

ENV NEXT_PUBLIC_DEFAULT_AVATAR_URL=$NEXT_PUBLIC_DEFAULT_AVATAR_URL
ENV NEXT_PUBLIC_GITHUB_AUTH_ENABLED=$NEXT_PUBLIC_GITHUB_AUTH_ENABLED
ENV NEXT_PUBLIC_DISCORD_AUTH_ENABLED=$NEXT_PUBLIC_DISCORD_AUTH_ENABLED
ENV NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=$NEXT_PUBLIC_GOOGLE_AUTH_ENABLED
ENV NEXT_PUBLIC_EMAIL_AUTH_ENABLED=$NEXT_PUBLIC_EMAIL_AUTH_ENABLED
ENV NEXT_PUBLIC_PAYMENTS_ENABLED=$NEXT_PUBLIC_PAYMENTS_ENABLED
ENV TIERS_JSON=$TIERS_JSON
ENV NEXT_PUBLIC_APP_DESC=$NEXT_PUBLIC_APP_DESC
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_FOOTER_LINKS=$NEXT_PUBLIC_FOOTER_LINKS
ENV NEXT_PUBLIC_NAVBAR_LINKS=$NEXT_PUBLIC_NAVBAR_LINKS
ENV NEXT_PUBLIC_FRONTEND_URL=$NEXT_PUBLIC_FRONTEND_URL
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_UPLOAD_LIMIT_BYTES=$NEXT_PUBLIC_UPLOAD_LIMIT_BYTES

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN echo "Building with placeholder envs..."
RUN bun run build

FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=0330
ENV HOST=0.0.0.0

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 0330
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["node", "server.js"]
